name: Chisel IP Contribution Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Verilator Build
      id: cache-verilator
      uses: actions/cache@v1
      with:
        path: verilator/root
        key: ${{ runner.os }}-build-${{ hashFiles('build_verilator.sh') }}-1

    - name: Compile Verilator from Source
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      run: ./build_verilator.sh
       
    - name: Add Verilator to Path
      run: |
       ls $GITHUB_WORKSPACE/verilator/root/bin/
       echo "::add-path::$GITHUB_WORKSPACE/verilator/root/bin/"

    - name: Print Verilator Version
      run: verilator --version

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile
      run: sbt compile

    - name: Test GCD
      run: sbt "testOnly gcd.**"

    - name: Test BitonicSorter
      run: sbt "testOnly chisel.lib.bitonicsorter.**"

    - name: Test Cordic
      run: sbt "testOnly chisel.lib.cordic.**"

    - name: Test UART
      run: sbt "testOnly chisel.lib.uart.**"

    - name: Test FIFO
      run: sbt "testOnly chisel.lib.fifo.**"

    - name: Test Decoupled Interface Lib
      run: sbt "testOnly chisel.lib.dclib.**"

    - name: Test ECC
      run: sbt "testOnly chisel.lib.ecc.**"
