name: Chisel IP Contribution Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Verilator from Ubuntu Package Sources
      run: |
        sudo apt-get install verilator -y
        verilator --version

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile
      run: sbt compile

    - name: Test GCD
      run: sbt "testOnly gcd.**"

    - name: Test BitonicSorter
      run: sbt "testOnly chisel.lib.bitonicsorter.**"

    - name: Test Cordic
      run: sbt "testOnly chisel.lib.cordic.**"

    - name: Test UART
      run: sbt "testOnly chisel.lib.uart.**"

    - name: Test FIFO
      run: sbt "testOnly chisel.lib.fifo.**"

    - name: Test Decoupled Interface Lib
      run: sbt "testOnly chisel.lib.dclib.**"

    - name: Test ECC
      run: sbt "testOnly chisel.lib.ecc.**"
